---
name: (Containerisation/Docker/Script - Test)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Containerisation/Docker/Script

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./Containerisation/Docker/Script

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./Containerisation/Docker/Script
